/*
 * Lerninhalte des Englisch-Trainers.
 *
 * Aufbau: jedes Deck hat eine stabile id (wird fuer den Lernfortschritt im
 * localStorage benutzt), eine Stufe nach GER und eine Wortliste. Ein Eintrag
 * ist ein Array [englisch, deutsch, Beispielsatz].
 *
 * Konventionen fuer die Wortliste:
 *   - Englische Verben ohne "to", englische Nomen ohne Artikel.
 *   - Deutsche Nomen mit Artikel, damit das Genus mitgelernt wird.
 *   - Mehrere gueltige Loesungen werden mit " / " getrennt, beim Abfragen
 *     zaehlt jede davon als richtig.
 *   - Klammern enthalten Zusatzinfos; sie duerfen beim Tippen weggelassen
 *     werden.
 */
window.VOCAB_DATA = {
  decks: [
    {
      id: "basics",
      title: "Grundwortschatz",
      level: "A1",
      blurb: "Die Woerter, die in fast jedem Satz vorkommen.",
      words: [
        ["house", "das Haus", "Their house is at the end of the street."],
        ["car", "das Auto", "My car is quite old but reliable."],
        ["water", "das Wasser", "Can I have a glass of water, please?"],
        ["friend", "der Freund / die Freundin", "She is my best friend."],
        ["day", "der Tag", "It was a long day at work."],
        ["night", "die Nacht", "We drove through the night."],
        ["book", "das Buch", "This book is really worth reading."],
        ["door", "die Tür", "Please close the door behind you."],
        ["window", "das Fenster", "Open the window, it is hot in here."],
        ["street", "die Straße", "They live on a quiet street."],
        ["city", "die Stadt", "London is a huge city."],
        ["country", "das Land", "Which country do you come from?"],
        ["money", "das Geld", "I do not have much money left."],
        ["job", "der Job / die Stelle", "He found a new job in Manchester."],
        ["name", "der Name", "What is your name?"],
        ["child", "das Kind", "Every child gets a free ticket."],
        ["woman", "die Frau", "The woman next to me was reading."],
        ["man", "der Mann", "An old man was feeding the birds."],
        ["dog", "der Hund", "Our dog barks at everyone."],
        ["cat", "die Katze", "The cat is sleeping on the sofa."],
        ["want", "wollen", "I want to learn English properly."],
        ["need", "brauchen", "We need more time for this."],
        ["ask", "fragen", "Can I ask you something?"],
        ["answer", "antworten / die Antwort", "Nobody could answer the question."],
        ["work", "arbeiten / die Arbeit", "She works from home on Fridays."],
        ["live", "leben / wohnen", "They live in a small village."],
        ["learn", "lernen", "You learn faster with short sessions."],
        ["use", "benutzen", "Do not use your phone while driving."],
        ["open", "oeffnen / offen", "The shop opens at nine."],
        ["close", "schließen", "They close early on Sundays."],
        ["big", "groß", "That is a big mistake."],
        ["small", "klein", "We rented a small flat."],
        ["new", "neu", "Is that a new jacket?"],
        ["old", "alt", "My laptop is five years old."],
        ["good", "gut", "The food was really good."],
        ["bad", "schlecht", "The weather was bad all week."],
        ["fast / quick", "schnell", "That was a quick answer."],
        ["slow", "langsam", "The train was very slow today."],
        ["easy", "einfach / leicht", "The test was easier than expected."],
        ["difficult / hard", "schwierig", "English spelling is difficult."]
      ]
    },
    {
      id: "family",
      title: "Familie & Menschen",
      level: "A1",
      blurb: "Verwandtschaft, Alter und Beziehungen.",
      words: [
        ["family", "die Familie", "My family lives in Hamburg."],
        ["parents", "die Eltern", "Her parents are both teachers."],
        ["mother / mum", "die Mutter", "My mother calls me every Sunday."],
        ["father / dad", "der Vater", "His father works at the airport."],
        ["daughter", "die Tochter", "Their daughter is turning six."],
        ["son", "der Sohn", "My son plays football."],
        ["sister", "die Schwester", "I share a room with my sister."],
        ["brother", "der Bruder", "My brother is two years older."],
        ["grandmother / grandma", "die Großmutter / die Oma", "My grandmother bakes the best cake."],
        ["grandfather / grandpa", "der Großvater / der Opa", "Grandpa told us old stories."],
        ["aunt", "die Tante", "My aunt lives in Ireland."],
        ["uncle", "der Onkel", "Uncle Tom picked us up."],
        ["cousin", "der Cousin / die Cousine", "My cousin is studying medicine."],
        ["wife", "die Ehefrau", "He met his wife at university."],
        ["husband", "der Ehemann", "Her husband is a nurse."],
        ["neighbour", "der Nachbar / die Nachbarin", "Our neighbour waters the plants."],
        ["colleague", "der Kollege / die Kollegin", "A colleague showed me the office."],
        ["boyfriend", "der Freund (Partner)", "She came with her boyfriend."],
        ["girlfriend", "die Freundin (Partnerin)", "His girlfriend studies law."],
        ["baby", "das Baby", "The baby slept the whole flight."],
        ["teenager", "der Teenager / der Jugendliche", "Most teenagers use this app."],
        ["adult", "der Erwachsene", "Two adults and one child, please."],
        ["married", "verheiratet", "They have been married for ten years."],
        ["single", "ledig / alleinstehend", "He is still single."],
        ["birthday", "der Geburtstag", "Her birthday is in April."],
        ["relative", "der Verwandte", "We invited all our relatives."]
      ]
    },
    {
      id: "food",
      title: "Essen & Trinken",
      level: "A1",
      blurb: "Einkaufen, kochen und im Restaurant bestellen.",
      words: [
        ["bread", "das Brot", "I bought fresh bread this morning."],
        ["butter", "die Butter", "There is no butter in the fridge."],
        ["cheese", "der Käse", "This cheese comes from France."],
        ["egg", "das Ei", "I eat an egg for breakfast."],
        ["milk", "die Milch", "Do you take milk in your tea?"],
        ["meat", "das Fleisch", "She does not eat meat."],
        ["chicken", "das Hähnchen / das Huhn", "We had chicken and rice."],
        ["fish", "der Fisch", "The fish was fresh and cheap."],
        ["fruit", "das Obst", "Fruit is cheaper in summer."],
        ["apple", "der Apfel", "An apple a day keeps the doctor away."],
        ["vegetables", "das Gemüse", "Add the vegetables at the end."],
        ["potato", "die Kartoffel", "Boil the potatoes for 20 minutes."],
        ["rice", "der Reis", "Rice takes about ten minutes."],
        ["salt", "das Salz", "This soup needs more salt."],
        ["sugar", "der Zucker", "No sugar in my coffee, thanks."],
        ["breakfast", "das Frühstück", "Breakfast is served until ten."],
        ["lunch", "das Mittagessen", "Let us have lunch together."],
        ["dinner", "das Abendessen", "Dinner is almost ready."],
        ["meal", "die Mahlzeit / das Gericht", "It was the best meal of the trip."],
        ["plate", "der Teller", "Put the plates on the table."],
        ["knife", "das Messer", "This knife is not sharp."],
        ["fork", "die Gabel", "I dropped my fork."],
        ["spoon", "der Löffel", "Use a spoon for the soup."],
        ["cup", "die Tasse", "Another cup of tea?"],
        ["bill / check", "die Rechnung", "Could we have the bill, please?"],
        ["waiter", "der Kellner", "The waiter was very friendly."],
        ["taste", "schmecken / der Geschmack", "It tastes better with lemon."],
        ["delicious", "lecker / köstlich", "That cake was delicious."],
        ["hungry", "hungrig", "I am really hungry now."],
        ["thirsty", "durstig", "Are you thirsty after the walk?"]
      ]
    },
    {
      id: "home",
      title: "Haus & Alltag",
      level: "A1",
      blurb: "Wohnen, Moebel und was man den ganzen Tag so tut.",
      words: [
        ["flat / apartment", "die Wohnung", "We rent a flat near the park."],
        ["room", "das Zimmer", "The room is small but bright."],
        ["kitchen", "die Küche", "The kitchen needs new lights."],
        ["bathroom", "das Badezimmer", "The bathroom is upstairs."],
        ["bedroom", "das Schlafzimmer", "My bedroom faces the garden."],
        ["living room", "das Wohnzimmer", "We watch films in the living room."],
        ["garden", "der Garten", "The garden is full of flowers."],
        ["floor", "der Boden / das Stockwerk", "They live on the third floor."],
        ["wall", "die Wand", "We painted the wall white."],
        ["roof", "das Dach", "The roof is leaking again."],
        ["table", "der Tisch", "Put your bag on the table."],
        ["chair", "der Stuhl", "This chair is uncomfortable."],
        ["bed", "das Bett", "I go to bed around eleven."],
        ["sofa / couch", "das Sofa", "The cat owns the sofa."],
        ["cupboard", "der Schrank", "The cups are in the cupboard."],
        ["fridge", "der Kühlschrank", "The fridge is empty again."],
        ["key", "der Schlüssel", "I lost my keys again."],
        ["light", "das Licht", "Turn off the light, please."],
        ["rent", "die Miete / mieten", "The rent went up last year."],
        ["clean", "sauber / putzen", "I clean the kitchen on Saturdays."],
        ["tidy up", "aufräumen", "Please tidy up your room."],
        ["wash", "waschen", "I wash my clothes twice a week."],
        ["cook", "kochen", "He cooks better than I do."],
        ["sleep", "schlafen", "I did not sleep well last night."],
        ["wake up", "aufwachen", "I wake up at half past six."],
        ["get dressed", "sich anziehen", "Get dressed, we are late."]
      ]
    },
    {
      id: "time",
      title: "Zeit, Zahlen & Wetter",
      level: "A1",
      blurb: "Termine machen, Uhrzeit verstehen, ueber das Wetter reden.",
      words: [
        ["today", "heute", "I have no time today."],
        ["tomorrow", "morgen", "See you tomorrow."],
        ["yesterday", "gestern", "Yesterday was a holiday."],
        ["week", "die Woche", "The course lasts six weeks."],
        ["month", "der Monat", "We move house next month."],
        ["year", "das Jahr", "It has been a difficult year."],
        ["hour", "die Stunde", "The trip takes two hours."],
        ["minute", "die Minute", "Give me five minutes."],
        ["morning", "der Morgen / der Vormittag", "I run every morning."],
        ["afternoon", "der Nachmittag", "Call me in the afternoon."],
        ["evening", "der Abend", "We usually eat in the evening."],
        ["weekend", "das Wochenende", "Have a nice weekend."],
        ["Monday", "der Montag", "The meeting is on Monday."],
        ["Wednesday", "der Mittwoch", "I have a class every Wednesday."],
        ["Saturday", "der Samstag", "The market is open on Saturday."],
        ["early", "früh", "You are early today."],
        ["late", "spät", "Sorry, I am a bit late."],
        ["always", "immer", "He is always on time."],
        ["never", "nie", "I never drink coffee at night."],
        ["sometimes", "manchmal", "Sometimes I take the bus."],
        ["often", "oft", "We often go hiking."],
        ["weather", "das Wetter", "What is the weather like?"],
        ["rain", "der Regen / regnen", "It rains a lot in November."],
        ["snow", "der Schnee / schneien", "It might snow tonight."],
        ["sun", "die Sonne", "The sun is finally out."],
        ["cloud", "die Wolke", "There is not a cloud in the sky."],
        ["wind", "der Wind", "The wind is really cold."],
        ["temperature", "die Temperatur", "The temperature drops at night."]
      ]
    },
    {
      id: "travel",
      title: "Reisen & Verkehr",
      level: "A2",
      blurb: "Vom Ticketkauf bis zum Hotel-Check-in.",
      words: [
        ["trip / journey", "die Reise", "It was a long journey."],
        ["flight", "der Flug", "Our flight was delayed by an hour."],
        ["airport", "der Flughafen", "The airport is 40 minutes away."],
        ["luggage", "das Gepäck", "My luggage did not arrive."],
        ["suitcase", "der Koffer", "Her suitcase was too heavy."],
        ["ticket", "die Fahrkarte / das Ticket", "I booked the tickets online."],
        ["train", "der Zug", "The train leaves from platform four."],
        ["platform", "der Bahnsteig / das Gleis", "Which platform does it leave from?"],
        ["bus stop", "die Bushaltestelle", "The bus stop is around the corner."],
        ["arrive", "ankommen", "We arrive at eight in the evening."],
        ["leave / depart", "abfahren / verlassen", "The ferry leaves at noon."],
        ["delay", "die Verspätung", "There is a delay of 30 minutes."],
        ["book", "buchen", "I booked a room for two nights."],
        ["hotel", "das Hotel", "The hotel was clean and quiet."],
        ["room key", "der Zimmerschlüssel", "I left the room key inside."],
        ["check in", "einchecken", "You can check in from 3 p.m."],
        ["map", "die Karte / der Stadtplan", "Do you have a map of the city?"],
        ["way", "der Weg", "Can you show me the way?"],
        ["turn left", "links abbiegen", "Turn left after the bridge."],
        ["straight ahead", "geradeaus", "Go straight ahead for 200 metres."],
        ["abroad", "im Ausland / ins Ausland", "She works abroad."],
        ["border", "die Grenze", "We crossed the border at night."],
        ["passport", "der Reisepass", "Do not forget your passport."],
        ["holiday / vacation", "der Urlaub / die Ferien", "We are on holiday next week."],
        ["beach", "der Strand", "The beach was almost empty."],
        ["seaside", "die Küste / das Meer", "They spent a week at the seaside."],
        ["sightseeing", "die Besichtigung", "We did some sightseeing in Rome."],
        ["get lost", "sich verlaufen", "We got lost in the old town."]
      ]
    },
    {
      id: "body",
      title: "Körper & Gesundheit",
      level: "A2",
      blurb: "Beim Arzt erklaeren, was fehlt.",
      words: [
        ["head", "der Kopf", "My head hurts."],
        ["hair", "das Haar / die Haare", "She cut her hair short."],
        ["eye", "das Auge", "He has green eyes."],
        ["ear", "das Ohr", "My left ear is blocked."],
        ["mouth", "der Mund", "Open your mouth, please."],
        ["tooth", "der Zahn", "I broke a tooth."],
        ["hand", "die Hand", "Wash your hands before dinner."],
        ["arm", "der Arm", "He broke his arm skiing."],
        ["leg", "das Bein", "My legs hurt after the run."],
        ["foot", "der Fuß", "I hurt my foot yesterday."],
        ["back", "der Rücken", "My back hurts from sitting."],
        ["stomach", "der Bauch / der Magen", "I have a stomach ache."],
        ["heart", "das Herz", "Running is good for the heart."],
        ["skin", "die Haut", "The sun is bad for your skin."],
        ["health", "die Gesundheit", "Health comes first."],
        ["illness / disease", "die Krankheit", "It is a common illness."],
        ["pain", "der Schmerz", "The pain is getting better."],
        ["cold", "die Erkältung", "I have a bad cold."],
        ["fever", "das Fieber", "The child has a high fever."],
        ["cough", "der Husten / husten", "The cough kept me awake."],
        ["hurt", "wehtun / verletzen", "Does it still hurt?"],
        ["medicine", "das Medikament", "Take the medicine after meals."],
        ["appointment", "der Termin", "I made an appointment for Friday."],
        ["treatment", "die Behandlung", "The treatment lasts three weeks."]
      ]
    },
    {
      id: "school",
      title: "Schule & Lernen",
      level: "A2",
      blurb: "Unterricht, Pruefungen und das Studium.",
      words: [
        ["school", "die Schule", "The school starts at eight."],
        ["subject", "das Fach", "Maths is my favourite subject."],
        ["teacher", "der Lehrer / die Lehrerin", "Our teacher speaks four languages."],
        ["pupil / student", "der Schüler / die Schülerin", "Each pupil gets a tablet."],
        ["homework", "die Hausaufgaben", "I still have to do my homework."],
        ["exam", "die Prüfung", "The exam takes 90 minutes."],
        ["test", "der Test / die Klassenarbeit", "We have a test on Monday."],
        ["mark / grade", "die Note", "She got a good mark."],
        ["pass", "bestehen", "He passed the exam easily."],
        ["fail", "durchfallen", "I failed my driving test twice."],
        ["practise", "üben", "You have to practise every day."],
        ["repeat", "wiederholen", "Could you repeat that, please?"],
        ["explain", "erklären", "Can you explain this rule again?"],
        ["understand", "verstehen", "I do not understand the question."],
        ["mistake", "der Fehler", "Everybody makes mistakes."],
        ["word", "das Wort", "I do not know this word."],
        ["sentence", "der Satz", "Write a full sentence."],
        ["translate", "übersetzen", "Do not translate word for word."],
        ["pronunciation", "die Aussprache", "Her pronunciation is very clear."],
        ["vocabulary", "der Wortschatz / die Vokabeln", "Build your vocabulary daily."],
        ["university", "die Universität", "She studies at university."],
        ["degree", "der Abschluss", "He has a degree in physics."]
      ]
    },
    {
      id: "work",
      title: "Arbeit & Büro",
      level: "B1",
      blurb: "Bewerbung, Meetings und E-Mails.",
      words: [
        ["company", "die Firma / das Unternehmen", "The company has 200 employees."],
        ["employee", "der Mitarbeiter / die Mitarbeiterin", "Every employee gets a laptop."],
        ["employer", "der Arbeitgeber", "My employer pays for the training."],
        ["boss / manager", "der Chef / die Chefin", "My boss is on holiday."],
        ["staff", "das Personal / die Belegschaft", "The whole staff was invited."],
        ["department", "die Abteilung", "She works in the sales department."],
        ["meeting", "die Besprechung / das Meeting", "The meeting was cancelled."],
        ["deadline", "die Frist / der Abgabetermin", "We missed the deadline."],
        ["task", "die Aufgabe", "That is not my task."],
        ["project", "das Projekt", "The project is behind schedule."],
        ["salary", "das Gehalt", "He asked for a higher salary."],
        ["application", "die Bewerbung", "I sent my application yesterday."],
        ["interview", "das Vorstellungsgespräch", "The interview went well."],
        ["experience", "die Erfahrung", "She has years of experience."],
        ["skill", "die Fähigkeit / die Kompetenz", "Communication is a key skill."],
        ["training", "die Schulung / die Ausbildung", "The training takes two days."],
        ["customer / client", "der Kunde / die Kundin", "The customer is waiting."],
        ["invoice", "die Rechnung (Firma)", "Please send the invoice by email."],
        ["contract", "der Vertrag", "Read the contract carefully."],
        ["notice", "die Kündigung / kündigen", "He handed in his notice."],
        ["apply for", "sich bewerben um", "I applied for three jobs."],
        ["hire", "einstellen", "They hired two new developers."],
        ["earn", "verdienen", "She earns more than her manager."],
        ["attend", "teilnehmen an", "Please attend the meeting."],
        ["schedule", "der Zeitplan / planen", "The schedule is very tight."],
        ["overtime", "die Überstunden", "I worked overtime all week."],
        ["shift", "die Schicht", "He works the night shift."],
        ["retire", "in Rente gehen", "My father retires next year."]
      ]
    },
    {
      id: "feelings",
      title: "Gefühle & Charakter",
      level: "B1",
      blurb: "Sagen, wie es einem geht und wie jemand ist.",
      words: [
        ["happy", "glücklich / froh", "I am happy for you."],
        ["sad", "traurig", "The ending was really sad."],
        ["angry", "wütend / verärgert", "Do not be angry with me."],
        ["afraid / scared", "ängstlich / Angst haben", "She is afraid of flying."],
        ["proud", "stolz", "We are proud of the team."],
        ["surprised", "überrascht", "I was surprised by the result."],
        ["disappointed", "enttäuscht", "He was disappointed with the grade."],
        ["nervous", "nervös", "I get nervous before presentations."],
        ["relaxed", "entspannt", "You look relaxed today."],
        ["bored", "gelangweilt", "The children were bored."],
        ["tired", "müde", "I am too tired to cook."],
        ["worried", "besorgt", "My parents were worried."],
        ["lonely", "einsam", "He felt lonely in the new city."],
        ["confident", "selbstbewusst / zuversichtlich", "She is confident about the exam."],
        ["kind", "freundlich / nett", "That was very kind of you."],
        ["polite", "höflich", "Try to be polite on the phone."],
        ["honest", "ehrlich", "To be honest, I forgot."],
        ["patient", "geduldig", "Be patient, it takes time."],
        ["lazy", "faul", "I feel lazy on Sundays."],
        ["reliable", "zuverlässig", "He is a reliable colleague."],
        ["generous", "großzügig", "That is a generous offer."],
        ["stubborn", "stur", "My brother is incredibly stubborn."],
        ["shy", "schüchtern", "She was shy as a child."],
        ["mood", "die Stimmung / die Laune", "He is in a bad mood."],
        ["feeling", "das Gefühl", "I had a strange feeling."],
        ["mind", "der Verstand / etwas ausmachen", "Do you mind if I open the window?"]
      ]
    },
    {
      id: "nature",
      title: "Natur & Umwelt",
      level: "B1",
      blurb: "Landschaft, Tiere und Klimathemen.",
      words: [
        ["tree", "der Baum", "The tree in front of the house is old."],
        ["forest / wood", "der Wald", "We walked through the forest."],
        ["field", "das Feld", "The fields are full of corn."],
        ["mountain", "der Berg", "The mountain is covered in snow."],
        ["river", "der Fluss", "The river flows through the city."],
        ["lake", "der See", "We swam in the lake."],
        ["sea / ocean", "das Meer / der Ozean", "The sea was rough."],
        ["island", "die Insel", "The island has 300 inhabitants."],
        ["bird", "der Vogel", "A bird was singing outside."],
        ["insect", "das Insekt", "There are fewer insects each year."],
        ["plant", "die Pflanze / pflanzen", "We planted a tree in the garden."],
        ["leaf", "das Blatt", "The leaves turn red in autumn."],
        ["soil / ground", "der Boden / die Erde", "The soil here is very dry."],
        ["air", "die Luft", "The air is cleaner in the mountains."],
        ["environment", "die Umwelt", "We must protect the environment."],
        ["climate change", "der Klimawandel", "Climate change affects everyone."],
        ["pollution", "die Verschmutzung", "Air pollution is a big problem."],
        ["waste / rubbish", "der Müll / der Abfall", "We produce too much waste."],
        ["recycle", "recyceln / wiederverwerten", "Glass is easy to recycle."],
        ["energy", "die Energie", "Solar energy is getting cheaper."],
        ["save", "sparen / retten", "We try to save water."],
        ["protect", "schützen", "The area is protected by law."],
        ["species", "die Art (Tier-/Pflanzenart)", "Many species are endangered."],
        ["endangered", "gefährdet / vom Aussterben bedroht", "Bees are endangered."]
      ]
    },
    {
      id: "irregular",
      title: "Unregelmäßige Verben",
      level: "A2",
      type: "forms",
      blurb: "Grundform, Simple Past und Past Participle in einem Rutsch.",
      words: [
        ["be - was - been", "sein", "I have been here since Monday."],
        ["become - became - become", "werden", "She became a doctor."],
        ["begin - began - begun", "beginnen", "The film has already begun."],
        ["break - broke - broken", "brechen / kaputt machen", "He broke his phone."],
        ["bring - brought - brought", "bringen", "She brought a friend."],
        ["build - built - built", "bauen", "They built the house themselves."],
        ["buy - bought - bought", "kaufen", "I bought it online."],
        ["catch - caught - caught", "fangen / erwischen", "We caught the last train."],
        ["choose - chose - chosen", "wählen / auswählen", "You chose the better option."],
        ["come - came - come", "kommen", "He has come a long way."],
        ["cost - cost - cost", "kosten", "It cost me a fortune."],
        ["cut - cut - cut", "schneiden", "I cut my finger."],
        ["do - did - done", "tun / machen", "I have done my homework."],
        ["draw - drew - drawn", "zeichnen", "She drew a map for us."],
        ["drink - drank - drunk", "trinken", "He has drunk three coffees."],
        ["drive - drove - driven", "fahren (Auto)", "We drove all night."],
        ["eat - ate - eaten", "essen", "Have you eaten yet?"],
        ["fall - fell - fallen", "fallen", "Prices have fallen again."],
        ["feel - felt - felt", "fühlen", "I felt sick after lunch."],
        ["find - found - found", "finden", "We found the keys."],
        ["fly - flew - flown", "fliegen", "They flew to Dublin."],
        ["forget - forgot - forgotten", "vergessen", "I forgot your name."],
        ["get - got - got / gotten", "bekommen / werden", "She got a new job."],
        ["give - gave - given", "geben", "He gave me good advice."],
        ["go - went - gone", "gehen / fahren", "They have gone home."],
        ["grow - grew - grown", "wachsen / anbauen", "The town has grown quickly."],
        ["have - had - had", "haben", "We had a great time."],
        ["hear - heard - heard", "hören", "I heard a strange noise."],
        ["hold - held - held", "halten", "She held my hand."],
        ["keep - kept - kept", "behalten / bewahren", "Keep the change."],
        ["know - knew - known", "wissen / kennen", "I knew it from the start."],
        ["learn - learnt - learnt", "lernen", "I learnt that at school."],
        ["leave - left - left", "verlassen / abfahren", "The train has left."],
        ["lose - lost - lost", "verlieren", "We lost the game."],
        ["make - made - made", "machen / herstellen", "It is made of wood."],
        ["mean - meant - meant", "bedeuten / meinen", "What does that mean?"],
        ["meet - met - met", "treffen", "We met in Berlin."],
        ["pay - paid - paid", "bezahlen", "I paid by card."],
        ["put - put - put", "legen / stellen", "Put it on the shelf."],
        ["read - read - read", "lesen", "I have read that book."],
        ["ride - rode - ridden", "reiten / fahren (Rad)", "He rode his bike to work."],
        ["ring - rang - rung", "klingeln / anrufen", "The phone rang twice."],
        ["run - ran - run", "laufen / rennen", "She has run a marathon."],
        ["say - said - said", "sagen", "He said nothing."],
        ["see - saw - seen", "sehen", "I have seen this film."],
        ["sell - sold - sold", "verkaufen", "They sold the car."],
        ["send - sent - sent", "senden / schicken", "I sent the email."],
        ["sing - sang - sung", "singen", "She sang beautifully."],
        ["sit - sat - sat", "sitzen", "We sat in the garden."],
        ["sleep - slept - slept", "schlafen", "I slept for ten hours."],
        ["speak - spoke - spoken", "sprechen", "Have you spoken to her?"],
        ["spend - spent - spent", "ausgeben / verbringen", "We spent a week there."],
        ["stand - stood - stood", "stehen", "He stood by the door."],
        ["swim - swam - swum", "schwimmen", "We swam in the lake."],
        ["take - took - taken", "nehmen", "It took two hours."],
        ["teach - taught - taught", "unterrichten / beibringen", "She taught me to cook."],
        ["tell - told - told", "erzählen / sagen", "Tell me the truth."],
        ["think - thought - thought", "denken", "I thought so."],
        ["understand - understood - understood", "verstehen", "Nobody understood the joke."],
        ["wear - wore - worn", "tragen (Kleidung)", "He wore a blue shirt."],
        ["win - won - won", "gewinnen", "We won the match."],
        ["write - wrote - written", "schreiben", "She has written three books."]
      ]
    },
    {
      id: "phrasal",
      title: "Phrasal Verbs",
      level: "B1",
      blurb: "Die Verbindungen, die man nicht woertlich uebersetzen darf.",
      words: [
        ["get up", "aufstehen", "I get up at six every day."],
        ["wake up", "aufwachen", "Wake up, it is late."],
        ["give up", "aufgeben", "Do not give up now."],
        ["look for", "suchen", "I am looking for my glasses."],
        ["look after", "sich kümmern um", "She looks after her neighbour."],
        ["look forward to", "sich freuen auf", "I look forward to the weekend."],
        ["find out", "herausfinden", "We found out the truth later."],
        ["turn on", "einschalten", "Turn on the radio, please."],
        ["turn off", "ausschalten", "Turn off the lights when you leave."],
        ["put on", "anziehen", "Put on your jacket."],
        ["take off", "ausziehen / abheben", "The plane took off on time."],
        ["pick up", "abholen / aufheben", "I will pick you up at eight."],
        ["call back", "zurückrufen", "Can you call me back later?"],
        ["hang on", "warten / dranbleiben", "Hang on a second."],
        ["carry on", "weitermachen", "Carry on, you are doing fine."],
        ["run out of", "ausgehen (Vorrat)", "We have run out of milk."],
        ["come across", "zufällig treffen / stoßen auf", "I came across an old photo."],
        ["deal with", "sich befassen mit / erledigen", "I will deal with it tomorrow."],
        ["get on with", "gut auskommen mit", "She gets on well with everyone."],
        ["get over", "überwinden", "It took him weeks to get over the flu."],
        ["set up", "einrichten / gründen", "They set up their own company."],
        ["work out", "trainieren / klappen", "It worked out in the end."],
        ["fill in", "ausfüllen", "Fill in the form, please."],
        ["hand in", "abgeben / einreichen", "Hand in your report by Friday."],
        ["point out", "hinweisen auf", "She pointed out the mistake."],
        ["go on", "weitergehen / passieren", "What is going on here?"],
        ["show up", "auftauchen / erscheinen", "He never showed up."],
        ["break down", "kaputtgehen / zusammenbrechen", "Our car broke down."],
        ["check out", "auschecken / anschauen", "Check out this website."],
        ["throw away", "wegwerfen", "Do not throw away the receipt."]
      ]
    },
    {
      id: "phrases",
      title: "Wichtige Redewendungen",
      level: "A2",
      blurb: "Saetze, die im Gespraech sofort weiterhelfen.",
      words: [
        ["How are you doing?", "Wie geht es dir?", "Hi Tom, how are you doing?"],
        ["Nice to meet you.", "Freut mich, dich kennenzulernen.", "Nice to meet you, I am Anna."],
        ["Could you say that again, please?", "Können Sie das bitte wiederholen?", "Sorry, could you say that again, please?"],
        ["I am afraid I do not understand.", "Ich fürchte, ich verstehe nicht.", "I am afraid I do not understand the form."],
        ["What does that mean?", "Was bedeutet das?", "What does this abbreviation mean?"],
        ["How do you spell that?", "Wie schreibt man das?", "How do you spell your surname?"],
        ["Could you speak more slowly?", "Könnten Sie langsamer sprechen?", "Could you speak more slowly, please?"],
        ["It does not matter.", "Das macht nichts.", "It does not matter, really."],
        ["Never mind.", "Schon gut. / Vergiss es.", "Never mind, I will do it myself."],
        ["I am sorry, I am late.", "Entschuldigung, ich bin zu spät.", "I am sorry I am late, the bus was delayed."],
        ["That sounds great.", "Das klingt super.", "Dinner at eight? That sounds great."],
        ["I would rather stay home.", "Ich würde lieber zu Hause bleiben.", "I would rather stay home tonight."],
        ["Do you mind if I sit here?", "Stört es Sie, wenn ich mich hierhin setze?", "Do you mind if I sit here?"],
        ["Let me think about it.", "Lass mich darüber nachdenken.", "Let me think about it until Friday."],
        ["It is up to you.", "Das liegt bei dir.", "Pizza or pasta? It is up to you."],
        ["I have no idea.", "Ich habe keine Ahnung.", "I have no idea where he is."],
        ["Take your time.", "Lass dir Zeit.", "Take your time, there is no rush."],
        ["That is a good point.", "Das ist ein guter Einwand.", "That is a good point, I had not thought of it."],
        ["I am just looking, thanks.", "Ich schaue mich nur um, danke.", "I am just looking, thanks."],
        ["Could I have the bill, please?", "Könnte ich bitte die Rechnung haben?", "Could I have the bill, please?"],
        ["See you soon.", "Bis bald.", "See you soon, take care."],
        ["Have a nice day.", "Schönen Tag noch.", "Thanks, and have a nice day."],
        ["I am not sure yet.", "Ich bin mir noch nicht sicher.", "I am not sure yet about the date."],
        ["What do you think?", "Was meinst du?", "That is my plan. What do you think?"]
      ]
    },
    {
      id: "falsefriends",
      title: "False Friends",
      level: "B2",
      blurb: "Woerter, die anders klingen, als sie gemeint sind.",
      words: [
        ["actually", "tatsächlich / eigentlich (nicht: aktuell)", "Actually, I have never been there."],
        ["currently", "aktuell / derzeit", "She is currently working abroad."],
        ["eventually", "schließlich / letztendlich (nicht: eventuell)", "Eventually, they agreed."],
        ["possibly", "eventuell / möglicherweise", "He might possibly join us."],
        ["become", "werden (nicht: bekommen)", "It became clear very quickly."],
        ["receive / get", "bekommen", "I received your message."],
        ["gift", "das Geschenk (nicht: Gift)", "Thanks for the lovely gift."],
        ["poison", "das Gift", "The plant contains a poison."],
        ["sensible", "vernünftig (nicht: sensibel)", "That is a sensible decision."],
        ["sensitive", "sensibel / empfindlich", "He is very sensitive to criticism."],
        ["chef", "der Küchenchef / der Koch", "The chef recommends the fish."],
        ["boss", "der Chef", "I asked my boss for a day off."],
        ["handy", "praktisch / nützlich (nicht: Handy)", "This tool is really handy."],
        ["mobile phone", "das Handy", "My mobile phone is dead."],
        ["brave", "mutig (nicht: brav)", "That was a brave decision."],
        ["well-behaved", "brav / artig", "The children were well-behaved."],
        ["billion", "die Milliarde (nicht: Billion)", "The company is worth a billion."],
        ["undertaker", "der Bestatter (nicht: Unternehmer)", "The undertaker organised everything."],
        ["entrepreneur", "der Unternehmer", "She is a successful entrepreneur."],
        ["rent", "mieten (nicht: Rente)", "We rent a flat in the centre."],
        ["pension", "die Rente", "He lives on a small pension."],
        ["menu", "die Speisekarte (nicht: Menü)", "Could I see the menu, please?"],
        ["set meal", "das Menü (Gericht)", "The set meal includes a dessert."],
        ["confection / sweets", "die Süßwaren (nicht: Konfektion)", "The shop sells sweets and cakes."]
      ]
    }
  ]
};
