# Alter zu Saisonbeginn 2026/27 (bekannte Spieler). Fehlende Werte werden im
# Build-Skript geschaetzt und als geschaetzt markiert.
AGES = {
    # FC Bayern
    "Harry Kane": 33, "Michael Olise": 24, "Joshua Kimmich": 31, "Luis Díaz": 29, "Jamal Musiala": 23,
    "Jonathan Tah": 30, "Dayot Upamecano": 27, "Konrad Laimer": 29, "Alphonso Davies": 25, "Serge Gnabry": 31,
    "Kim Min Jae": 29, "Ismael Saibari": 25, "Aleksandar Pavlović": 22, "Manuel Neuer": 40, "Leon Goretzka": 31,
    "Raphaël Guerreiro": 32, "Nicolas Jackson": 25, "Josip Stanišić": 26, "Hiroki Ito": 27, "Tom Bischof": 21,
    "Jonas Urbig": 23, "Lennart Karl": 18, "Sven Ulreich": 38, "David Santos Daiber": 18, "Leon Klanac": 19,
    # Dortmund
    "Gregor Kobel": 28, "Nico Schlotterbeck": 26, "Serhou Guirassy": 30, "Felix Nmecha": 25, "Waldemar Anton": 30,
    "Julian Brandt": 30, "Emre Can": 32, "Karim Adeyemi": 24, "Marcel Sabitzer": 32, "Julian Ryerson": 28,
    "Maximilian Beier": 23, "Ramy Bensebaini": 31, "Fábio Silva": 24, "Daniel Svensson": 24, "Niklas Süle": 31,
    "Carney Chukwuemeka": 22, "Yan Couto": 24, "Jobe Bellingham": 21, "Salih Özcan": 28, "Alexander Meyer": 35,
    "Patrick Drewes": 33, "Almugera Kabar": 20, "Filippo Mane": 21, "Silas Ostrzinski": 23,
    # Leverkusen
    "Grimaldo": 31, "Aleix García": 29, "Patrik Schick": 30, "Exequiel Palacios": 28, "Edmond Tapsoba": 27,
    "Malik Tillman": 24, "Robert Andrich": 32, "Martin Terrier": 29, "Ibrahim Maza": 20, "Mark Flekken": 33,
    "Nathan Tella": 27, "Loïc Badé": 26, "Jonas Hofmann": 34, "Ezequiel Fernández": 24, "Jarell Quansah": 23,
    "Ernest Poku": 22, "Christian Kofane": 20, "Eliesse Ben Seghir": 21, "Janis Blaswich": 35, "Jonas Omlin": 32,
    "Arthur": 23, "Tim Oermann": 23, "Axel Tape": 18, "Niklas Lomb": 33, "Jeremiah Mensah": 18,
    # Leipzig
    "Péter Gulácsi": 36, "Willi Orban": 34, "David Raum": 28, "Castello Lukeba": 23, "Christoph Baumgartner": 27,
    "Yan Diomande": 19, "Benjamin Henrichs": 29, "Nicolas Seiwald": 25, "Ridle Baku": 28, "Xaver Schlager": 29,
    "Antonio Nusa": 21, "Rômulo": 24, "Johan Bakayoko": 23, "Kevin Kampl": 35, "Maarten Vandevoordt": 24,
    "Lukas Klostermann": 30, "El Chadaille Bitshiabu": 21, "Conrad Harder": 21, "Brajan Gruda": 22,
    "Assan Ouédraogo": 20, "Ezechiel Banzuzi": 21, "Kosta Nedeljković": 20, "Andrija Maksimović": 19,
    "Max Finkgräfe": 22, "Tidiam Gomis": 20, "Leopold Zingerle": 32, "Viggo Gebel": 18,
    # Frankfurt
    "Jonathan Burkardt": 26, "Ritsu Doan": 28, "Robin Koch": 30, "Raphael Onyedika": 25, "Can Uzun": 20,
    "Arthur Theate": 26, "Hugo Larsson": 22, "Mario Götze": 34, "Farès Chaïbi": 23, "Ansgar Knauff": 24,
    "Jean-Mattéo Bahoya": 21, "Elye Wahi": 23, "Michael Zetterer": 31, "Oscar Højlund": 21, "Nnamdi Collins": 22,
    "Noël Aséko": 21, "Niels Nkounkou": 25, "Ayoube Amaimouni": 21, "Elias Baum": 27, "Kauã Santos": 23,
    "Younes Ebnoutalib": 23, "Keita Kosugi": 20, "Jessic Ngankam": 26, "Timmy Chandler": 36, "Jens Grahl": 38,
    "Noel Futkeu": 23, "Love Arrhov": 18, "Malik Pimpong": 19,
    # Stuttgart
    "Angelo Stiller": 25, "Maximilian Mittelstädt": 29, "Deniz Undav": 30, "Alexander Nübel": 30,
    "Ermedin Demirović": 28, "Julian Chabot": 28, "Bilal El Khannouss": 22, "Jamie Leweling": 25,
    "Chris Führich": 28, "Tiago Tomás": 24, "Atakan Karazor": 29, "Lorenz Assignon": 26, "Josha Vagnoman": 26,
    "Dan-Axel Zagadou": 27, "Badredine Bouanani": 21, "Finn Jeltsch": 20, "Ramon Hendriks": 25,
    "Nikolas Nartey": 26, "Chema Andrés": 25, "Ameen Al Dakhil": 24, "Fabian Bredlow": 31, "Luca Jaquez": 23,
    "Pascal Stenzel": 30, "Justin Diehl": 21, "Jeremy": 21, "Lazar Jovanović": 20, "Noah Darvich": 19,
    # Freiburg
    "Matthias Ginter": 32, "Vincenzo Grifo": 33, "Philipp Lienhart": 30, "Noah Atubolu": 24, "Christian Günter": 33,
    "Johan Manzambi": 21, "Jan-Niklas Beste": 27, "Maximilian Eggestein": 29, "Lukas Kübler": 33, "Yuito Suzuki": 24,
    "Patrick Osterhage": 26, "Philipp Treu": 25, "Igor Matanović": 23, "Max Rosenfelder": 23,
    "Derry Scherhant": 23, "Lucas Höler": 32, "Florian Müller": 28, "Jordy Makengo": 25, "Nicolas Höfler": 36,
    "Anthony Jung": 34, "Daniel-Kofi Kyereh": 30, "Cyriaque Irié": 20, "Jannik Huth": 32, "Maximilian Philipp": 32,
    "Bruno Ogbus": 21, "Yannik Engelhardt": 25,
    # Augsburg
    "Jeffrey Gouweleeuw": 35, "Chrislain Matsima": 24, "Alexis Claude-Maurice": 28, "Finn Dahmen": 28,
    "Dimitris Giannoulis": 30, "Kristijan Jakić": 29, "Keven Schlotterbeck": 29, "Michael Gregoritsch": 32,
    "Han-Noah Massengo": 25, "Cédric Zesiger": 28, "Arne Maier": 27, "Fabian Rieder": 24, "Arthur Chaves": 25,
    "Robin Fellhauer": 28, "Marius Wolf": 31, "Elvis Rexhbeçaj": 29, "Anton Kade": 22, "Nediljko Labrović": 27,
    "Ismaël Gharbi": 22, "Mert Kömür": 20, "Mads Pedersen": 30, "Yannik Keitel": 26, "Noahkai Banks": 19,
    "Rodrigo Ribeiro": 21, "Thomas Kastanaras": 23, "Oliver Sorg": 36,
    # Hoffenheim
    "Oliver Baumann": 36, "Andrej Kramarić": 35, "Fisnik Asllani": 24, "Vladimír Coufal": 34, "Adam Hložek": 24,
    "Grischa Prömel": 31, "Wouter Burger": 25, "Leon Avdullahu": 22, "Bazoumana Touré": 20, "Ozan Kabak": 26,
    "Tim Lemperle": 24, "Robin Hranáč": 26, "Koki Machida": 29, "Bernardo": 31, "Alexander Prass": 25,
    "Albian Hajdari": 23, "Ihlas Bebou": 32, "Valentin Gendrey": 26, "Kevin Akpoguma": 31, "Muhammed Damar": 22,
    "Max Moerstedt": 20, "Luca Philipp": 26, "Cole Campbell": 20, "Deniz Zeitler": 20, "Adam Daghim": 21,
    "Nathan De Cat": 18, "Luka Đurić": 21, "Luca Erlein": 22,
    # Union
    "Frederik Rønnow": 34, "Leopold Querfeld": 22, "Rani Khedira": 32, "Derrick Köhn": 27, "Christopher Trimmel": 39,
    "Andrej Ilić": 26, "Zeno Van den Bosch": 23, "Michel Aebischer": 29, "András Schäfer": 27,
    "Aljoscha Kemlein": 22, "Josip Juranović": 31, "Oliver Burke": 29, "Janik Haberer": 32, "Tom Rothe": 21,
    "Ilyas Ansah": 21, "Jeong Woo Yeong": 27, "Robert Skov": 30, "Tim Skarke": 29, "Livan Burcu": 22,
    "Stanley Nsoki": 27, "Emmanuel Latte Lath": 27, "Matheo Raab": 27, "Marin Ljubičić": 24, "Carl Klaus": 32,
    # Gladbach
    "Tim Kleindienst": 31, "Franck Honorat": 30, "Rocco Reitz": 24, "Robin Hack": 28, "Moritz Nicolas": 29,
    "Nico Elvedi": 30, "Kevin Diks": 30, "Florian Neuhaus": 29, "Philipp Sander": 28, "Joe Scally": 23,
    "Haris Tabaković": 32, "Kevin Stöger": 33, "Jens Castrop": 23, "Shuto Machino": 27, "Giovanni Reyna": 23,
    "Lukas Ullrich": 22, "Marvin Friedrich": 30, "Nathan Ngoumou": 26, "Kota Takai": 22, "Hugo Bolin": 22,
    "Fabio Chiarodia": 21, "Jan Olschowsky": 24, "Tiago Pereira Cardoso": 20, "Tobias Sippel": 38,
    # Koeln
    "Marvin Schwäbe": 31, "Saïd El Mala": 20, "Ellyes Skhiri": 31, "Ragnar Ache": 28, "Thijs Dallinga": 26,
    "Sebastian Sebulonsen": 26, "Alessio Castro-Montes": 29, "Tom Krauß": 25, "Ísak Bergmann Jóhannesson": 23,
    "Marius Bülter": 33, "Gideon Mensah": 28, "Ron-Robert Zieler": 37, "Luca Waldschmidt": 30, "Linton Maina": 27,
    "Jan Thielmann": 24, "Jahmai Simpson-Pusey": 21, "Timo Hübers": 30, "Joël Schmied": 28, "Rav van den Berg": 21,
    "Imad Rondić": 27, "Malek El Mala": 21,
    # HSV
    "Daniel Heuer Fernandes": 33, "Luka Vušković": 19, "Fábio Vieira": 26, "Albert Sambi Lokonga": 26,
    "Miro Muheim": 28, "Jordan Torunarigha": 29, "Jean-Luc Dompé": 31, "Albert Grønbæk": 25, "Nicolás Capaldo": 28,
    "Philip Otele": 27, "Nicolai Remberg": 26, "Yussuf Poulsen": 32, "Warmed Omari": 26, "Robert Glatzel": 32,
    "Daniel Elfadli": 29, "Rayan Philippe": 26, "Emir Sahiti": 27, "Ransford-Yeboah Königsdörffer": 25,
    "Giorgi Gocholeishvili": 25, "Damion Downs": 22, "Sander Tangvik": 24, "Bakery Jatta": 28,
    "William Mikelbrencis": 22, "Noah Katterbach": 25, "Guilherme Ramos": 29, "Levin Öztunalı": 30,
    "Fabio Baldé": 21, "Otto Stange": 19,
    # Werder
    "Victor Boniface": 25, "Jens Stage": 30, "Mitchell Weiser": 32, "Romano Schmid": 26, "Marco Friedl": 28,
    "Cameron Puertas": 28, "Senne Lynen": 27, "Amos Pieper": 28, "Felix Agu": 27, "Yukinari Sugawara": 26,
    "Mio Backhaus": 22, "Niklas Stark": 31, "Marco Grüll": 28, "Maximilian Wöber": 28, "Samuel Mbangula": 22,
    "Leonardo Bittencourt": 32, "Karl Hein": 24, "Justin Njinmah": 25, "Isaac Schmidt": 27, "Olivier Deman": 29,
    "Karim Coulibaly": 19, "Julián Malatini": 25, "Keke Topp": 22, "Markus Kolke": 36,
    # Mainz
    "Kaishū Sano": 25, "Nadiem Amiri": 30, "Robin Zentner": 32, "Anthony Caci": 29, "Paul Nebel": 23,
    "Lee Jae-sung": 34, "Eric Martel": 24, "Benedict Hollerbach": 25, "Danny da Costa": 33, "Sheraldo Becker": 31,
    "Alexander Schwolow": 34, "Silvan Widmer": 33, "Fabio Gruber": 23,
    # Schalke
    "Edin Džeko": 40, "Dejan Ljubičić": 29, "Kenan Karaman": 32, "Moussa N'Diaye": 24, "Loris Karius": 33,
    "Kevin Müller": 35, "Moussa Sylla": 26, "Nikola Katić": 29, "Timo Becker": 29, "Hasan Kuruçay": 29,
    "Soufiane El-Faouzi": 22, "Adil Aouchiche": 24, "Ron Schallenberg": 27, "Finn Porath": 29,
    "Christopher Antwi-Adjei": 32, "Amin Younes": 33, "Tomáš Kalas": 33, "Adrian Gantenbein": 25,
    "Vitalie Becker": 23, "Mertcan Ayhan": 26, "Janik Bachmann": 30, "Bryan Lasme": 27, "Felipe Sánchez": 22,
    "Anton Donkor": 28, "Max Grüger": 21, "Christian Gomis": 21, "Henning Matriciani": 26, "Emil Højlund": 21,
    "Peter Remmert": 21, "Luca Podlech": 19, "Tidiane Toure": 20,
    # Elversberg / Paderborn
    "Nicolas Kristof": 27, "Lukas Petkov": 26, "Lukas Pinckert": 26, "Tom Zimmerschied": 28, "Maximilian Rohr": 31,
    "Immanuel Pherai": 25, "Florian Le Joncour": 31, "Łukasz Poręba": 26, "Bambasé Conté": 23, "Jan Gyamerah": 31,
    "Lasse Günther": 23, "Amara Condé": 29, "Felix Keidel": 22, "Luca Schnellbacher": 32, "Luca Pfeiffer": 29,
    "Carlo Sickinger": 29, "Manuel Feil": 31, "David Mokwa": 22, "Nicholas Mickelson": 26, "Tim Boss": 32,
    "Frank Lehmann": 37, "Raphael Obermair": 30, "Felix Götze": 28, "Filip Bilbija": 26, "Calvin Brackelmann": 27,
    "Laurin Curda": 24, "Santiago Castañeda": 22, "Tjark Scheller": 23, "Dennis Seimen": 20, "Mika Baur": 22,
    "Sven Michel": 36, "Marcel Hoffmeier": 27, "Nick Bätzner": 23, "Steffen Tigges": 28, "Mattes Hansen": 22,
    "Sebastian Klaas": 28, "David Kinsombi": 27, "Markus Schubert": 28, "Lucas Copado": 22, "Kennedy Okpala": 22,
    "Ruben Müller": 21, "Bennit Bröger": 20, "Jonah Sticker": 21, "Stefano Marino": 21,
    # 2. Bundesliga
    "Kamil Grabara": 27, "Mohamed Amoura": 26, "Maximilian Arnold": 32, "Lovro Majer": 28, "Joakim Mæhle": 29,
    "Patrick Wimmer": 25, "Denis Vavro": 30, "Jonas Wind": 27, "Konstantinos Koulierakis": 22,
    "Mattias Svanberg": 27, "Vinicius Souza": 27, "Moritz Jenz": 27, "Saël Kumbedi": 21, "Yannick Gerhardt": 32,
    "Jesper Lindstrøm": 26, "Marius Müller": 33, "Aaron Zehnter": 21, "Kilian Fischer": 25, "Kevin Paredes": 23,
    "Rogério": 28, "Bence Dárdai": 20, "Dženan Pejčinović": 21, "Pavao Pervan": 38, "Jeanuël Belocian": 21,
    "Jonas Adjetey": 22, "Kento Shiogai": 21, "Jenson Seelt": 23, "Christian Eriksen": 34,
    "Patrick Mainka": 32, "Niklas Dorsch": 28, "Tim Siersleben": 26, "Budu Zivzivadze": 32,
    "Arijon Ibrahimović": 20, "Christian Conteh": 26, "Paul Tschernuth": 24,
    "Nikola Vasilj": 30, "Jackson Irvine": 33, "Eric Smith": 29, "Hauke Wahl": 32, "Mathias Pereira Lage": 29,
    "Mathias Rasmussen": 28, "Manolis Saliakas": 30, "Martijn Kaars": 27, "James Sands": 26,
    "Joel Chima Fujita": 24, "Karol Mets": 33, "Danel Sinani": 29, "David Nemeth": 25, "Andréas Hountondji": 24,
    "Louis Oppie": 24, "Arkadiusz Pyrka": 24, "Connor Metcalfe": 27, "Lars Ritzka": 28, "Adam Dźwigała": 30,
    "Ricky-Jade Jones": 23, "Ben Voll": 25, "Abdoulie Ceesay": 22, "Erik Ahlstrand": 24, "Jannik Robatsch": 21,
    "Fin Stevens": 23, "Simon Spari": 25,
    "Enzo Leopold": 26, "Benjamin Källman": 28, "Maurice Neubauer": 23, "Boris Tomiak": 28, "Noah Weißhaupt": 24,
    "Elias Saad": 26, "Daisuke Yokota": 26, "Virgil Ghiță": 28, "Mustapha Bundu": 29,
    "Stefán Teitur Þórðarson": 28, "Maik Nawrocki": 25, "Waniss Taïbi": 24, "Benedikt Pichler": 29,
    "Nahuel Noll": 23, "Ime Okon": 22, "Husseyn Chakroun": 23, "Hayate Matsuda": 27, "Håvard Nielsen": 33,
    "Franz Roggow": 23, "Bastian Allgeier": 23, "Leo Weinkauf": 30, "Williams Kokolo": 26,
    "Isac Lidberg": 28, "Killian Corredor": 26, "Marcel Schuhen": 33, "Niklas Schmidt": 28, "Fabian Nürnberger": 27,
    "Sergio López": 27, "Fynn Lakenmacher": 26,
    "Mergim Berisha": 28, "Naatan Skyttä": 24, "Paul Joly": 26, "Luca Sirch": 27,
    "Fabian Reese": 28, "Josip Brekalo": 28, "Michaël Cuisance": 27, "Dawid Kownacki": 29,
    "Julian Justvan": 28, "Finn Ole Becker": 26, "Rabby Nzingoula": 21, "Luka Lochoshvili": 28, "Rafael Lubach": 21,
    "Berkay Yilmaz": 21, "Jan Reichert": 25, "Ondřej Karafiát": 32,
    "Kevin Vogt": 35, "Timo Horn": 33, "Matúš Bero": 30, "Maximilian Wittek": 31, "Philipp Hofmann": 33,
    "Oliver Olsen": 26, "Gerrit Holtmann": 31, "Ibrahim Sissoko": 31, "Philipp Strompf": 28, "Koji Miyoshi": 29,
    "Erhan Mašović": 28, "Moritz-Broni Kwarteng": 28, "Noah Loosli": 29, "Leandro Morgalla": 21, "Cajetan Lenz": 22,
    "Kjell Wätjen": 20, "Francis Onyeka": 20, "Callum Marshall": 22, "Niclas Thiede": 27, "Mats Pannewig": 22,
    "Farid Alfa-Ruprecht": 20, "Mikkel Rakneberg": 22,
    "Marvin Wanitzek": 33, "Marcel Franke": 33, "Sebastian Jung": 36, "Fabian Schleusener": 34, "David Herold": 23,
    "Marcel Beifus": 23, "Nicolai Rapp": 30, "Dženis Burnić": 28, "Christoph Kobald": 29, "Stephan Ambrosius": 27,
    "Kwon Hyeok Kyu": 25, "Hans Christian Bernat": 26, "Roko Šimić": 22, "Louey Ben Farhat": 19,
    "Robin Himmelmann": 37, "Lilian Egloff": 23, "Shio Fukuda": 22, "Leon Opitz": 21, "Paul Scholl": 21, "Aki Koch": 20,
    "Niklas Hauptmann": 30, "Christoph Daferner": 28, "Alexander Rossipal": 30, "Robert Wagner": 23,
    "Elias Bethke": 23, "Jakob Lemmer": 26, "Tim Schreiber": 24, "Thomas Keller": 27, "Vincent Vermeij": 32,
    "Jonas Sterner": 24, "Lennart Grill": 27, "Lukas Boeder": 29, "Ben Bobzien": 23, "Julian Pauli": 21,
    "Kofi Jeremy Amoako": 21, "Lars Bünning": 28, "Claudio Kammerknecht": 27, "Nils Fröling": 26,
    "Jason Ceka": 26, "Luca Herrmann": 27, "Sascha Risch": 25, "Stefan Kutschke": 37, "Jan Hendrik Marx": 31,
    "John Tolkin": 24, "Jonas Meffert": 32, "David Zec": 26, "Steven Skrzybski": 33, "Giorgi Kvilitaia": 32,
    "Phil Harres": 24, "Jonas Therkelsen": 24, "Adrián Kaprálik": 24, "Timon Weiner": 27, "Lasse Rosenboom": 23,
    "Kasper Davidsen": 22, "Marko Ivezić": 26, "Hiroki Sekine": 23, "Ivan Nekić": 24, "Guillermo Balzi": 25,
    "Gyan de Regt": 22, "Faride Alidou": 25, "Sebastian Schonlau": 32, "Taisei Abe": 25, "Andu Kelati": 21,
    "Frederik Roslyng": 21, "Marcel Engelhardt": 33, "Marcus Müller": 21,
    "Ron-Thorben Hoffmann": 27, "Lino Tempelmann": 27, "Mehmet Can Aydın": 24, "Maximilian Entrup": 29,
    "Kevin Ehlers": 25, "Robin Heußer": 28, "Max Marie": 22, "Johan Gómez": 24, "Fabio Di Michele Sanchez": 22,
    "Aaron Opoku": 27, "Florian Flick": 26, "Lukas Frenkert": 25, "Andi Hoti": 23, "Frederik Jäkel": 25,
    "Yann Sturm": 22, "Louis Breunig": 22, "Samuele Di Benedetto": 21, "Sanoussy Ba": 22, "Sidi Sané": 23,
    "Jovan Mijatović": 21, "Damjan Kovačević": 22, "Jan Urbich": 20,
    "Tolcay Ciğerci": 31, "Erik Engelhardt": 28, "Dominik Pelivan": 30, "Timmy Thiele": 34, "Axel Borgmann": 32,
    "Henry Rorig": 22, "Leon Guwara": 29, "Tim Campulka": 30, "King Samuel Manu": 22, "Moritz Hannemann": 25,
    "Jonas Hofmann": 34, "Lukas Michelbrink": 26, "Justin Butler": 23, "Erik Tallig": 26, "Ted Tattermusch": 22,
    "Alexander Sebald": 25,
    # 3. Liga
    "Dominik Kother": 26, "Christian Viet": 27, "Lex-Tyger Lobinger": 27, "Joshua Bitter": 29, "Aljaž Casar": 26,
    "Patrick Sussek": 26, "Rasim Bulić": 26, "Jakob Bookjans": 26, "Can Coşkun": 28, "Maximilian Braune": 23,
    "Alexander Hahn": 33, "Tobias Fleckstein": 27, "Conor Noß": 25, "Steffen Meuer": 28, "Jan-Simon Symalla": 23,
    "Maximilian Dittgen": 31, "Leon Müller": 24, "Florian Egerer": 31, "Thilo Töpken": 27, "Niklas Jessen": 24,
    "Mert Göckan": 25, "Dennis Borkowski": 24, "Ben Schlicke": 20, "Tim Heike": 24, "Moritz Montag": 23,
    "Julius Paris": 22,
    "Lars Dietz": 29, "David Otto": 27, "Frank Ronstadt": 29, "Simon Handle": 24, "Florian Engelhardt": 29,
    "Christoph Greger": 29, "Soichiro Kozuki": 26, "Meiko Sponsel": 24, "Leonhard Münst": 24, "Tim Kloss": 24,
    "Tobias Eisenhuth": 22, "Lucas Wolf": 21, "Arne Schulz": 25, "Kevin Rauhut": 37, "Joel Agyekum": 22,
    "Benjamin Uphoff": 33, "Ahmet Gürleyen": 27, "Andreas Voglsammer": 34, "Marco Schuster": 31,
    "Florian Carstens": 27, "Adrien Lebeau": 27, "Maximilian Krauß": 29, "Jan Mejdr": 22, "Franz Pfanne": 32,
    "Christian Kinsombi": 26, "Viktor Bergh": 23, "Nico Neidhart": 32, "Emil Holten": 30, "Cedric Harenbrock": 28,
    "Benno Dietze": 21, "Kenan Fatkić": 28, "Paul Stock": 23, "Felix Ruschke": 25, "Lukas Wallner": 23,
    "Jonas Dirkner": 22, "Philipp Klewin": 33, "Dario Gebuhr": 22, "Dominik Lanius": 25, "David Hummel": 21,
    "Tim Krohn": 22,
    "Felix Lohkemper": 31, "Arianit Ferati": 29, "Terrence Boyd": 35, "Lukas Klünter": 30, "Thijmen Nijhuis": 28,
    "Niklas Hoffmann": 29, "Samuel Abifade": 21, "Sascha Voelcke": 27, "Nicklas Shipnoski": 28,
    "Tim Sechelmann": 29, "Adama Diakhaby": 30, "Julian Rieckmann": 32, "Emmanuel Iwe": 25,
    "Maximilian Thalhammer": 28, "Diego Michel": 23, "Oluwaseun Ogbemudia": 19, "Rico Benatelli": 34,
    "Kushtrim Asallari": 22, "Lucien Hawryluk": 22, "Jascha Brandt": 22, "Seyhan Yigit": 21,
    "Jorrit Hendrix": 31, "Dominique Heintz": 33, "Tim Oberdorf": 30, "Philipp Förster": 31, "Andreas Müller": 26,
    "Matthias Zimmermann": 34, "Yassine Bouchama": 23, "Lasse Rieß": 24, "Steven van der Sloot": 24,
    "Elias Egouli": 21, "Marcel Benger": 28, "Eric Hottmann": 26, "Jomaine Consbruch": 24, "Jordi Paulina": 23,
    "Miguel Gonçalves": 21, "Lukas Eixler": 21, "Louis Lord": 22, "Noah Egouli": 20, "Milán Czakó": 21,
    "Kilian Sauck": 19, "Kaden Amaniampong": 20, "Hamza Anhari": 20, "Felix Meiser": 19, "Anas Slimani": 20,
    "Berkan Taz": 28, "Philipp Schulze": 31, "Timur Gayret": 30, "Martin Ens": 25, "Oualid Mhamdi": 24,
    "Yari Otto": 23, "Niko Kijewski": 30, "Dennis Waidner": 21, "Jonas Arweiler": 28, "Joshua Eze": 24,
    "Alessio Besio": 22, "Michel Stöcker": 21, "Fabian Wessig": 25, "Julian Stark": 25, "Dominik Steczyk": 27,
    "Almin Mešanović": 23, "Tobias Knost": 26, "Paul Lehmann": 22, "Lukas Demming": 21, "Marco Wörner": 22,
    "Marlon Zacharias": 21,
    "Felix Gebhardt": 24, "Julian Pollersbeck": 31, "Benedikt Saller": 34, "Leopold Wurm": 21, "Andreas Geipl": 34,
    "Christian Kühlwetter": 30, "Sebastian Stolze": 31, "Adrian Fein": 27, "Philipp Müller": 23,
    "Malte Karbstein": 28, "Robin Ziegele": 29, "Felix Strauss": 25, "Noel Eichinger": 25,
    "Oscar Schönfelder": 25, "Florian Dietz": 27, "Phil Beckhoff": 24, "Alexander Weidinger": 29,
    "Dejan Galjen": 23, "Benedikt Bauer": 21, "Lucas Hermes": 22, "Leo Mätzler": 21,
    "Nicolas-Bernd Oliveira": 24, "Nick Seidel": 21,
    "Tim Rossmann": 22, "Kwasi Okyere Wriedt": 32, "Omer Hanin": 28, "Jesse Tugbenyo": 22, "Robin Velasco": 22,
    "Enzo Wirtz": 21, "Jasper Löffelsend": 29, "Florian Pick": 31, "Calogero Rizzuto": 34,
    "Patrick Sontheimer": 28, "Niko Bretschneider": 27, "Dominic Baumann": 31, "Mladen Cvjetinović": 23,
    "Anton Bäuerle": 21, "Fredrik Carlsen": 24, "Nishan Velupillay": 25, "Manuel Riemann": 38, "Mika Schroers": 24,
    "Gianluca Gaudino": 29, "Jakob Golz": 28, "Lucas Brumme": 27, "José-Enrique Ríos Alonso": 26,
    "Jaka Čuber Potočnik": 21, "Joshua Mees": 30, "Marvin Schulz": 31, "Rico Preißinger": 30,
    "Charalambos Makridis": 30, "Florian Stritzel": 32, "Philipp Hercher": 30, "Moritz Flotho": 22,
    "Niklas May": 24, "Tarik Gözüsirin": 32, "Max Brandt": 30, "Philipp Ochs": 29, "Ersin Zehir": 28,
    "Christopher Olivier": 22, "Nuha Jatta": 21, "David Tritschler": 20, "Efe Korkut": 19,
    "Tim Handwerker": 28, "Robin Knoche": 34, "Maximilian Bauer": 26, "Henri Koudossou": 27, "Lukas Kunze": 28,
    "Barış Atik": 31, "Alexander Nollenberger": 29, "Maximilian Dietz": 24, "Reno Münz": 21, "Benjamin Zank": 23,
    "Leander Popp": 21, "Adrian Beck": 29, "Robin Meißner": 26, "Julian Kania": 22, "Konrad Faber": 28,
    "Mason Toye": 27, "Lars Lokotsch": 30,
}
