# Vereinsstammdaten Saison 2026/27.
# file: Rohdatei in raw/, colors: Primär-/Sekundärfarbe (keine Wappen, nur Farben),
# rep: Reputation 1-100, money: Kontostand zu Saisonbeginn in Mio. EUR.

LEAGUES = [
    {"id": "bl", "name": "Bundesliga", "short": "BL", "level": 1},
    {"id": "bl2", "name": "2. Bundesliga", "short": "2. BL", "level": 2},
    {"id": "l3", "name": "3. Liga", "short": "3. Liga", "level": 3},
    {"id": "rl", "name": "Regionalliga", "short": "RL", "level": 4},
]

CLUBS = [
    # --- Bundesliga ---
    dict(id="fcb", file="fcb", league="bl", name="FC Bayern München", short="Bayern", abbr="FCB", colors=["#DC052D", "#FFFFFF"], stadium="Allianz Arena", cap=75024, rep=98, money=180),
    dict(id="bvb", file="bvb", league="bl", name="Borussia Dortmund", short="Dortmund", abbr="BVB", colors=["#FDE100", "#111111"], stadium="Signal Iduna Park", cap=81365, rep=90, money=95),
    dict(id="b04", file="b04", league="bl", name="Bayer 04 Leverkusen", short="Leverkusen", abbr="B04", colors=["#E32221", "#111111"], stadium="BayArena", cap=30210, rep=88, money=85),
    dict(id="rbl", file="rbl", league="bl", name="RB Leipzig", short="Leipzig", abbr="RBL", colors=["#FFFFFF", "#DD0741"], stadium="Red Bull Arena", cap=47069, rep=85, money=80),
    dict(id="sge", file="sge", league="bl", name="Eintracht Frankfurt", short="Frankfurt", abbr="SGE", colors=["#E1000F", "#111111"], stadium="Deutsche Bank Park", cap=58000, rep=82, money=60),
    dict(id="vfb", file="vfb", league="bl", name="VfB Stuttgart", short="Stuttgart", abbr="VFB", colors=["#FFFFFF", "#E32219"], stadium="MHPArena", cap=60449, rep=81, money=50),
    dict(id="scf", file="scf", league="bl", name="SC Freiburg", short="Freiburg", abbr="SCF", colors=["#E2001A", "#111111"], stadium="Europa-Park Stadion", cap=34700, rep=76, money=40),
    dict(id="m05", file="m05", league="bl", name="1. FSV Mainz 05", short="Mainz", abbr="M05", colors=["#C3141E", "#FFFFFF"], stadium="MEWA Arena", cap=33305, rep=71, money=25),
    dict(id="svw", file="svw", league="bl", name="SV Werder Bremen", short="Bremen", abbr="SVW", colors=["#1D9053", "#FFFFFF"], stadium="Weserstadion", cap=42100, rep=74, money=20),
    dict(id="fca", file="fca", league="bl", name="FC Augsburg", short="Augsburg", abbr="FCA", colors=["#BA3733", "#46714D"], stadium="WWK Arena", cap=30660, rep=68, money=22),
    dict(id="tsg", file="tsg", league="bl", name="TSG Hoffenheim", short="Hoffenheim", abbr="TSG", colors=["#1C63B7", "#FFFFFF"], stadium="PreZero Arena", cap=30150, rep=72, money=40),
    dict(id="fcu", file="fcu", league="bl", name="1. FC Union Berlin", short="Union", abbr="FCU", colors=["#EB1923", "#FFFFFF"], stadium="An der Alten Försterei", cap=22012, rep=70, money=25),
    dict(id="bmg", file="bmg", league="bl", name="Borussia Mönchengladbach", short="Gladbach", abbr="BMG", colors=["#111111", "#1A9F3D"], stadium="Borussia-Park", cap=54042, rep=75, money=30),
    dict(id="koe", file="koe", league="bl", name="1. FC Köln", short="Köln", abbr="KOE", colors=["#ED1C24", "#FFFFFF"], stadium="RheinEnergieStadion", cap=50000, rep=72, money=18),
    dict(id="hsv", file="hsv", league="bl", name="Hamburger SV", short="HSV", abbr="HSV", colors=["#0A3F86", "#FFFFFF"], stadium="Volksparkstadion", cap=57000, rep=74, money=22),
    dict(id="s04", file="s04", league="bl", name="FC Schalke 04", short="Schalke", abbr="S04", colors=["#004D9D", "#FFFFFF"], stadium="Veltins-Arena", cap=62271, rep=75, money=12),
    dict(id="sve", file="sve", league="bl", name="SV Elversberg", short="Elversberg", abbr="SVE", colors=["#111111", "#FFFFFF"], stadium="Ursapharm-Arena", cap=10000, rep=55, money=10),
    dict(id="scp", file="scp", league="bl", name="SC Paderborn 07", short="Paderborn", abbr="SCP", colors=["#005CA9", "#111111"], stadium="Home Deluxe Arena", cap=15000, rep=58, money=10),
    # --- 2. Bundesliga ---
    dict(id="wob", file="wob", league="bl2", name="VfL Wolfsburg", short="Wolfsburg", abbr="WOB", colors=["#65B32E", "#FFFFFF"], stadium="Volkswagen Arena", cap=28917, rep=70, money=38),
    dict(id="fch", file="fch2", league="bl2", name="1. FC Heidenheim 1846", short="Heidenheim", abbr="FCH", colors=["#E2001A", "#003B79"], stadium="Voith-Arena", cap=15000, rep=60, money=16),
    dict(id="stp", file="stp", league="bl2", name="FC St. Pauli", short="St. Pauli", abbr="STP", colors=["#624839", "#FFFFFF"], stadium="Millerntor-Stadion", cap=29546, rep=64, money=14),
    dict(id="h96", file="h96", league="bl2", name="Hannover 96", short="Hannover", abbr="H96", colors=["#C8102E", "#111111"], stadium="Heinz von Heiden Arena", cap=49000, rep=64, money=10),
    dict(id="d98", file="d98", league="bl2", name="SV Darmstadt 98", short="Darmstadt", abbr="D98", colors=["#004C99", "#FFFFFF"], stadium="Merck-Stadion am Böllenfalltor", cap=17810, rep=57, money=7),
    dict(id="fck", file="fck", league="bl2", name="1. FC Kaiserslautern", short="Lautern", abbr="FCK", colors=["#D00027", "#FFFFFF"], stadium="Fritz-Walter-Stadion", cap=49780, rep=63, money=8),
    dict(id="bsc", file="bsc", league="bl2", name="Hertha BSC", short="Hertha", abbr="BSC", colors=["#005CA9", "#FFFFFF"], stadium="Olympiastadion", cap=74475, rep=67, money=6),
    dict(id="fcn", file="fcn", league="bl2", name="1. FC Nürnberg", short="Nürnberg", abbr="FCN", colors=["#8B0D1E", "#111111"], stadium="Max-Morlock-Stadion", cap=50000, rep=62, money=8),
    dict(id="boc", file="boc", league="bl2", name="VfL Bochum 1848", short="Bochum", abbr="BOC", colors=["#005CA9", "#FFFFFF"], stadium="Vonovia Ruhrstadion", cap=26000, rep=61, money=10),
    dict(id="ksc", file="ksc", league="bl2", name="Karlsruher SC", short="Karlsruhe", abbr="KSC", colors=["#004C99", "#FFFFFF"], stadium="BBBank Wildpark", cap=34302, rep=58, money=6),
    dict(id="sgd", file="sgd", league="bl2", name="Dynamo Dresden", short="Dresden", abbr="SGD", colors=["#FDD200", "#111111"], stadium="Rudolf-Harbig-Stadion", cap=32066, rep=58, money=6),
    dict(id="ksv", file="ksv", league="bl2", name="Holstein Kiel", short="Kiel", abbr="KSV", colors=["#004C99", "#E30613"], stadium="Holstein-Stadion", cap=15034, rep=58, money=9),
    dict(id="dsc", file="dsc", league="bl2", name="Arminia Bielefeld", short="Bielefeld", abbr="DSC", colors=["#004E95", "#111111"], stadium="SchücoArena", cap=26515, rep=58, money=6),
    dict(id="fcm", file="fcm", league="bl2", name="1. FC Magdeburg", short="Magdeburg", abbr="FCM", colors=["#0055A4", "#FFFFFF"], stadium="Avnet Arena", cap=30098, rep=56, money=6),
    dict(id="ebs", file="ebs", league="bl2", name="Eintracht Braunschweig", short="Braunschweig", abbr="EBS", colors=["#FFD700", "#00428C"], stadium="Eintracht-Stadion", cap=23325, rep=56, money=5),
    dict(id="sgf", file="sgf", league="bl2", name="SpVgg Greuther Fürth", short="Fürth", abbr="SGF", colors=["#009639", "#FFFFFF"], stadium="Sportpark Ronhof", cap=16626, rep=55, money=6),
    dict(id="osn", file="vfl", league="bl2", name="VfL Osnabrück", short="Osnabrück", abbr="OSN", colors=["#5B2D8B", "#FFFFFF"], stadium="Bremer Brücke", cap=15741, rep=52, money=3),
    dict(id="fce", file="fce", league="bl2", name="FC Energie Cottbus", short="Cottbus", abbr="FCE", colors=["#E30613", "#FFFFFF"], stadium="LEAG Energie Stadion", cap=22528, rep=50, money=3),
    # --- 3. Liga ---
    dict(id="msv", file="msv", league="l3", name="MSV Duisburg", short="Duisburg", abbr="MSV", colors=["#004B93", "#FFFFFF"], stadium="Schauinsland-Reisen-Arena", cap=31514, rep=52, money=3),
    dict(id="vik", file="vik", league="l3", name="FC Viktoria Köln", short="Viktoria", abbr="VIK", colors=["#E2001A", "#FFFFFF"], stadium="Sportpark Höhenberg", cap=8343, rep=40, money=1.5),
    dict(id="rwe", file="rwe", league="l3", name="Rot-Weiss Essen", short="Essen", abbr="RWE", colors=["#E2001A", "#FFFFFF"], stadium="Stadion an der Hafenstraße", cap=19962, rep=50, money=2.5),
    dict(id="fcs", file="fcs", league="l3", name="1. FC Saarbrücken", short="Saarbrücken", abbr="FCS", colors=["#0060AA", "#111111"], stadium="Ludwigsparkstadion", cap=16003, rep=48, money=2.5),
    dict(id="tsg2", file="tsg2", league="l3", name="TSG Hoffenheim II", short="Hoffenheim II", abbr="TSG2", colors=["#1C63B7", "#FFFFFF"], stadium="Dietmar-Hopp-Stadion", cap=6350, rep=36, money=1.5, reserve="tsg"),
    dict(id="hro", file="fch", league="l3", name="FC Hansa Rostock", short="Rostock", abbr="HRO", colors=["#004C99", "#FFFFFF"], stadium="Ostseestadion", cap=29000, rep=54, money=3),
    dict(id="aac", file="aac", league="l3", name="Alemannia Aachen", short="Aachen", abbr="AAC", colors=["#FFDD00", "#111111"], stadium="Tivoli", cap=32960, rep=48, money=2),
    dict(id="prm", file="scp2", league="l3", name="SC Preußen Münster", short="Münster", abbr="PRM", colors=["#00843D", "#111111"], stadium="LVM-Preußenstadion", cap=14300, rep=48, money=2),
    dict(id="wal", file="svw2", league="l3", name="SV Waldhof Mannheim", short="Mannheim", abbr="WAL", colors=["#004C99", "#111111"], stadium="Carl-Benz-Stadion", cap=25667, rep=48, money=2),
    dict(id="f95", file="f95", league="l3", name="Fortuna Düsseldorf", short="Düsseldorf", abbr="F95", colors=["#DA251D", "#FFFFFF"], stadium="Merkur Spiel-Arena", cap=54600, rep=58, money=6),
    dict(id="scv", file="scv", league="l3", name="SC Verl", short="Verl", abbr="SCV", colors=["#111111", "#FFFFFF"], stadium="Sportclub Arena", cap=5207, rep=38, money=1.2),
    dict(id="fko", file="fko", league="l3", name="SC Fortuna Köln", short="Fortuna Köln", abbr="FKÖ", colors=["#E2001A", "#FFFFFF"], stadium="Südstadion", cap=11748, rep=36, money=1),
    dict(id="sgs", file="sgs", league="l3", name="SG Sonnenhof Großaspach", short="Großaspach", abbr="SGS", colors=["#111111", "#F2C200"], stadium="WIRmachenDRUCK Arena", cap=10001, rep=34, money=1),
    dict(id="fci", file="fci", league="l3", name="FC Ingolstadt 04", short="Ingolstadt", abbr="FCI", colors=["#111111", "#E2001A"], stadium="Audi Sportpark", cap=15200, rep=50, money=3),
    dict(id="vfb2", file="vfb2", league="l3", name="VfB Stuttgart II", short="Stuttgart II", abbr="VFB2", colors=["#FFFFFF", "#E32219"], stadium="GAZi-Stadion auf der Waldau", cap=11410, rep=36, money=1.5, reserve="vfb"),
    dict(id="fwk", file="fwk", league="l3", name="FC Würzburger Kickers", short="Würzburg", abbr="FWK", colors=["#E2001A", "#FFFFFF"], stadium="Akon Arena", cap=13090, rep=40, money=1.2),
    dict(id="svm", file="svm", league="l3", name="SV Meppen", short="Meppen", abbr="SVM", colors=["#004C99", "#FFFFFF"], stadium="Hänsch-Arena", cap=13815, rep=38, money=1),
    dict(id="jah", file="ssv", league="l3", name="SSV Jahn Regensburg", short="Regensburg", abbr="JAH", colors=["#E2001A", "#FFFFFF"], stadium="Jahnstadion Regensburg", cap=15210, rep=48, money=2),
    dict(id="sww", file="sww", league="l3", name="SV Wehen Wiesbaden", short="Wiesbaden", abbr="SVWW", colors=["#E2001A", "#111111"], stadium="BRITA-Arena", cap=15295, rep=46, money=2),
    dict(id="hav", file="hav", league="l3", name="TSV Havelse", short="Havelse", abbr="HAV", colors=["#004C99", "#FFFFFF"], stadium="Eilenriedestadion", cap=5000, rep=32, money=0.8),
    # --- Regionalliga-Pool (nur fuer Auf-/Abstieg, nicht simuliert) ---
    dict(id="m60", file="r60", league="rl", name="TSV 1860 München", short="1860", abbr="M60", colors=["#79A6D2", "#FFFFFF"], stadium="Grünwalder Stadion", cap=15000, rep=50, money=1.5),
    dict(id="aue", file="rau", league="rl", name="FC Erzgebirge Aue", short="Aue", abbr="AUE", colors=["#5B2D8B", "#FFFFFF"], stadium="Erzgebirgsstadion", cap=16485, rep=44, money=1),
    dict(id="ulm", file="rulm", league="rl", name="SSV Ulm 1846", short="Ulm", abbr="ULM", colors=["#111111", "#FFFFFF"], stadium="Donaustadion", cap=17400, rep=42, money=1),
    dict(id="sw05", file="rsw", league="rl", name="1. FC Schweinfurt 05", short="Schweinfurt", abbr="S05", colors=["#009639", "#FFFFFF"], stadium="Sachs-Stadion", cap=15060, rep=34, money=0.6),
]
